#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

current_branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo "no-branch")

git add .

if [ "$current_branch" = "main" ]; then
  echo 'Building code'
  if ! dotnet build --no-restore; then
    echo "Build failed. Aborting push."
    exit 1
  fi

  echo 'Formatting code'
  if ! dotnet format --no-restore; then
    echo "Code formatting failed. Aborting push."
    exit 1
  fi

  echo 'Running tests'
  if ! dotnet test --no-restore; then
    echo "Tests failed. Aborting push."
    exit 1
  fi
else
  echo "Not pushing to main branch, skipping build, format, and test steps."
fi