#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# main 브랜치에 커밋될 때만 실행
if [ "$current_branch" = "main" ]; then
  echo 'Building code'
  dotnet build

  echo 'Formatting code'
  dotnet format

  echo 'Running tests'
  dotnet test
else
  echo 'Not on main branch, skipping build, format, and test steps.'
fi